# Generated by Django 2.2.2 on 2019-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('contacted_on_updates', models.BooleanField(blank=True)),
                ('description', models.TextField()),
                ('photo', models.FileField(upload_to='uploads/')),
                ('agree_to_clauses', models.BooleanField()),
            ],
        ),
    ]
