# Generated by Django 2.2.2 on 2019-06-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='followed_up',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
