# Generated by Django 2.2.2 on 2019-07-01 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_submission', '0003_fault_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='date_of_creation',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
