# Generated by Django 2.2.3 on 2019-07-23 14:51

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_submission', '0004_auto_20190701_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
